.import TILES
.import ITEMS

;	TILES listing
;	
;	00 - Grass
;	02 - Player
;	04 - Inserter 1 1
;	06 - Inserter 1 2
;	08 - Inserter 1 3
;	10 - Assembler1 1
;	12 - Assembler1 2
;	14 - Assembler1 3 ---- This is the mark between itemable tiles
;	16 - Conveyor 1 1
; 	18 - Conveyor 1 2
;	20 - Conveyor 1 3
;	22 - Conveyor 2 1
;	24 - Conveyor 2 2
;	26 - Conveyor 2 3
;
;
;
;	ITEMS listing
;	00 - Blank
;	02 - Green Ore 1
;	04 - Green Ore 2
; 	06 - Green Ore 3