.import TILES
.import ITEMS

;	TILES listing
;	
;	00 - Grass
;	02 - Inserter 1 1
;	04 - Inserter 1 2
;	06 - Inserter 1 3
;	08 - Assembler1 1
;	10 - Assembler1 2
;	12 - Assembler1 3 ---- This is the mark between itemable tiles
;	14 - Conveyor 1 1
; 	16 - Conveyor 1 2
;	18 - Conveyor 1 3
;	20 - Conveyor 2 1
;	22 - Conveyor 2 2
;	24 - Conveyor 2 3
;
;
;
;	ITEMS listing
;	00 - Blank
;	02 - Green Ore 1
;	04 - Green Ore 2
; 	06 - Green Ore 3